version: "3.8"

services:
  redis:
    image: redis:7-alpine
    container_name: laravel-test-redis
    command: [ "redis-server", "--save", "20", "1", "--loglevel", "warning" ]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

  k6:
    image: grafana/k6:0.50.0
    container_name: laravel-test-k6
    working_dir: /app
    entrypoint: ["k6"]
    volumes:
      - ./:/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - redis

volumes:
  redis-data:

